### ISSUE TITLE
Failed to clone Git repository/go install because of LFS data quota

### ISSUE THREAD

**Issue by sergerdn** [randolphcyg/gowireshark#10]
Forking this repository didn't solve the issue, which I believe is a bug of GitHub because forking some repo should use my _Git LFS_ limits, not from the original repo.

I wrote this issue to inform you that some people may encounter issues with cloning your repo, and forking your repos _will not solve_ their problems.

Also, `go build github.com/randolphcyg/gowireshark` affected this issue.

```
$ git clone https://github.com/randolphcyg/gowireshark.git
Cloning into 'gowireshark'...
remote: Enumerating objects: 14005, done.
remote: Counting objects: 100% (1989/1989), done.
remote: Compressing objects: 100% (1127/1127), done.
Receiving objects: 100% (14005/14005), 79.15 MiB | 15.41 MiB/s, done. 12016

Resolving deltas: 100% (5941/5941), done.
Updating files: 100% (6808/6808), done.
Downloading libs/libpcap.so.1 (1.2 MB)
Error downloading object: libs/libpcap.so.1 (c70bf5a): Smudge error: Error downloading libs/libpcap.so.1 (c70bf5a9379985c368e257b30359b886506f4c442052bf1cd4436660279eea8c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'D:\Projects\GolandProjects\github\gowireshark\.git\lfs\logs\20230911T002107.9409077.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: libs/libpcap.so.1: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by randolphcyg** [comment]
Thank you for the reminder！In fact, I encountered this LFS bug after submitting last month, and I am waiting for github to increase the LFS capacity for free users on October 1 to update the library;
If you need the latest code for this project, maybe you can leave an email and I'll send it to you first.

**Comment by randolphcyg** [comment]
> @randolphcyg
> 
> I also want to inform you that the project has encountered issues on https://github.com/randolphcyg/gowireshark/releases. I downloaded the latest archive, but it does not contain all the necessary files because LFS.

Due to limited LFS width, I can't upload the DLL file corresponding to wireshark version 4.0.8:
```
libs/libwireshark.so
libs/libwireshark.so.16
libs/libwireshark.so.16.0.8
libs/libwiretap.so
libs/libwiretap.so.13
libs/libwiretap.so.13.0.8
libs/libwsutil.so
libs/libwsutil.so.14
libs/libwsutil.so.14.0.0
```
I plan to upload it on October 1st after github adjusts the LFS limit.
I just uploaded the libs folder to the cloud disk as a temporary solution :[gowireshark-libs](https://drive.google.com/drive/folders/1V-h60podfRDsgPmHUC1C8YM1LB6bQHH1?usp=drive_link)
V2.0.9 lacks these files, you can try it.
