### ISSUE TITLE
unable to build the code on mac m1

### ISSUE THREAD

**Issue by ugandhar84** [randolphcyg/gowireshark#11]
unable to build the code on mac m1- are there nay dependencies?

# github.com/randolphcyg/gowireshark
In file included from frame_tvbuff.c:15:
In file included from ./include/wireshark/epan/packet.h:16:
In file included from ./include/wireshark/epan/proto.h:34:
In file included from ./include/wireshark/epan/tvbuff.h:30:
In file included from ./include/wireshark/wsutil/ws_mempbrk.h:16:
/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/emmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
In file included from frame_tvbuff.c:15:
In file included from ./include/wireshark/epan/packet.h:16:
In file included from ./include/wireshark/epan/proto.h:34:
In file included from ./include/wireshark/epan/tvbuff.h:30:
In file included from ./include/wireshark/wsutil/ws_mempbrk.h:16:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/emmintrin.h:17:
/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
In file

**Comment by randolphcyg** [comment]
`emmintrin.h`、`xmmintrin.h` are only meant to be used on x86 and x64 architecture, so there is no need to try it on Mac m1 anymore.

**Comment by randolphcyg** [comment]
When I compiled the libpcap and wireshark 4.0.10 versions of the Mac dynamic link library, I found that it was tested correctly on the Mac
```
.
├── libpcap.1.dylib
├── libwireshark.16.0.10.dylib
├── libwireshark.16.dylib
├── libwireshark.dylib
├── libwiretap.13.0.10.dylib
├── libwiretap.13.dylib
├── libwiretap.dylib
├── libwsutil.14.0.0.dylib
├── libwsutil.14.dylib
└── libwsutil.dylib
```

**Comment by randolphcyg** [comment]
Wireshark 4.0.10 dynamic link libraries for Ubuntu 22 and Mac M1 systems are stored here：
https://drive.google.com/drive/folders/1V-h60podfRDsgPmHUC1C8YM1LB6bQHH1?usp=drive_link
