### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by meeas** [randolphcyg/gowireshark#7]
```
$ go install "github.com/randolphcyg/gowireshark@latest"
go: downloading github.com/randolphcyg/gowireshark v1.10.6
go: github.com/randolphcyg/gowireshark@latest: create zip: module source tree too large (max size is 524288000 bytes)
```

Running on Fedora 37, fully patched, with functional go 1.19.8 and many other golang libraries/apps installed.

**Comment by randolphcyg** [comment]
Go get or go install has a size limit, you can use git clone to pull projects, sorry, I've been busy with other emails lately
