### ISSUE TITLE
issue in testing huge file print all frames

### ISSUE THREAD

**Issue by ugandhar84** [randolphcyg/gowireshark#9]
/gowireshark/tests/gowireshark_test.go:33 +0x25
testing.tRunner(0xc000110ea0, 0x57d100)
        /usr/lib/go-1.18/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/lib/go-1.18/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    github.com/randolphcyg/gowireshark/tests        600.690s

**Comment by randolphcyg** [comment]
the same problem in https://github.com/randolphcyg/gowireshark/issues/8
